name: Docker Runner Self Hosted

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Lint Dockerfile
      run: hadolint Dockerfile --ignore DL3018 --ignore SC2005 --ignore SC2086

    - name: Docker Build
      run: docker build --no-cache -t my-clicks-app:v2 .

    - name: Trivy Image Scan
      run: trivy image my-clicks-app:v2

    - name: Trivy FS Scan
      run: trivy fs .

    - name: Run container
      run: docker run -d -p 3025:80 my-clicks-app:v2

    - name: ACR Login
      run: az acr login --name acr1h4is53m79d

    - name: Docker Tag
      run: docker tag my-clicks:v2 acr1h4is53m79d.azurecr.io/my-clicks:v2

    - name: Docker Push
      run: docker push acr1h4is53m79d.azurecr.io/my-clicks:v2

    - name: K8s Login
      run: az aks get-credentials --name "aks1-k8s" --resource-group "aks1-k8s-resources" --overwrite-existing

    - name: K8s deploy
      run: kubectl apply -f .\pod-K8s-ACRImage.yaml
